CREATE TABLE XXFS_REQUEST_DETAILS 
   (	
   "REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"OBJECT_VERSION_NUM" NUMBER NOT NULL ENABLE, 
	"ITERATION_NUM" NUMBER NOT NULL ENABLE, 
	"REQUEST_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"REQUESTER_ID" NUMBER NOT NULL ENABLE, 
	"PERSON_ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_DATE" DATE, 
	"REQUEST_DATA" CLOB NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"REQUEST_STATUS" VARCHAR2(30 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(64 BYTE), 
	"REQUEST_NUMBER" VARCHAR2(30 BYTE), 
	"APPROVER_ID" VARCHAR2(240 BYTE), 
	"APPROVER_EMAIL_ID" VARCHAR2(240 BYTE), 
	"APPROVER_LEVEL" NUMBER, 
	"INTEGRATION_STATUS" VARCHAR2(60 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(240 BYTE), 
	"TRANSACTION_ID" NUMBER, 
	"APPROVER_NUMBER" VARCHAR2(500 BYTE), 
	"CATEGORY" VARCHAR2(150 BYTE), 
	"PERSONABSENCEENTRYID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "XXFS_REQUEST_DETAILS_CHK" CHECK ( request_data IS JSON ) ENABLE, 
	 CONSTRAINT "XXFS_REQUEST_DETAILS_PK" PRIMARY KEY ("REQUEST_ID")
     );
     
CREATE SEQUENCE REQUEST_ID_S INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999 MINVALUE 1 NOCACHE;



alter table departments_json   add constraint dept_data_json   check ( department_data is json );
