.context.fetchOptions.filterCriterion
.context.fetchOptions.filterCriterion.text

configuration.hookHandler.context.fetchOptions.filterCriterion
configuration.hookHandler.context.fetchOptions.filterCriterion.text
