SELECT 
START_DATE,
TO_DATE(START_DATE,'DD-MON-YYYY') AS DATE_FOR1,
TO_DATE(TO_DATE(START_DATE,'DD-MON-YYYY'), 'DD-MM-YYYY') AS DATE_FOR2,
TO_CHAR(TO_DATE(TO_DATE(START_DATE,'DD-MON-YYYY'), 'DD-MM-YYYY'), 'MM/DD/RR') AS DATE_FOR3
FROM XXQIA_VACATION_RULES
