WITH MONTH_C AS (Select to_char(sysdate,'MON-YYYY') AS CURRENT_MONTH,to_char(ADD_MONTHS(sysdate,1),'MON-YYYY') AS NEXT_MONTH,to_char(ADD_MONTHS(sysdate,-1),'MON-YYYY') AS PREV_MONTH from dual)
SELECT COLVALUE FROM MONTH_C 
UNPIVOT (COLVALUE FOR COL IN (CURRENT_MONTH,NEXT_MONTH,PREV_MONTH))ORDER BY COLVALUE DESC
